"""AstroWoof natal semantic-basis extraction and authoring runtime."""

from importlib.metadata import PackageNotFoundError, version
import logging


# Library consumers should not receive surprise stderr output merely by importing
# SBE.  Command entry points install the operational handler explicitly.
logging.getLogger(__name__).addHandler(logging.NullHandler())

try:
    __version__ = version("astrowoof-natal-authoring")
except PackageNotFoundError:
    __version__ = "0.4.0.dev0"

from .reconciliation import (  # noqa: E402
    ProviderReconciliationAdapters,
    reconcile_authoring_provider_cycle,
)
from .native_transitions import (  # noqa: E402
    NativeTransitionResultView,
    latest_native_transition_result,
    read_native_transition_result,
    validate_transition_journal,
)
from .route_parity import (  # noqa: E402
    read_bounded_route_parity_traces,
    read_route_parity_oracle,
    validate_bounded_route_traces,
    validate_route_parity_oracle,
)
from .initial_wave import (  # noqa: E402
    InitialWaveError,
    build_initial_wave_binding_bundle,
    build_wave_authorization,
    preflight_wave_authorization,
    validate_initial_wave,
    validate_initial_wave_binding_bundle,
    validate_initial_wave_binding_bundle_against_wave,
    validate_initial_wave_result,
    validate_wave_authorization_document,
)
from .initial_wave_contract import (  # noqa: E402
    build_initial_wave_authority_inputs,
    read_initial_wave_authority_inputs,
    read_initial_wave_fixture,
    read_initial_wave_schema,
    validate_initial_wave_fixture,
    validate_initial_wave_authority_inputs,
)
from .deployed_qa import (  # noqa: E402
    read_deployed_qa_schema,
    run_deployed_qa_qualification,
    validate_deployed_qa_receipt,
)
from .response_diagnostics import (  # noqa: E402
    inspect_response,
    read_response_retrieval_diagnostic_schema,
    validate_response_retrieval_diagnostic,
)
from .lifecycle_contracts import (  # noqa: E402
    validate_lifecycle_inspection_v04,
    validate_lifecycle_inspection_v05,
)
from .temporal_lifecycle import (  # noqa: E402
    build_external_authority_request_v2,
    build_lifecycle_inspection_v06,
    canonical_utc_instant,
    inspect_temporal_lifecycle,
    read_temporal_external_authority_schema,
    read_temporal_lifecycle_schema,
    temporal_transition_errors,
    validate_external_authority_request_v2,
    validate_external_authority_request_v2_against_inspection,
    validate_lifecycle_inspection_v06,
    validate_temporal_transition,
)
from .pending_lifecycle_qa import (  # noqa: E402
    run_provider_pending_lifecycle_qualification,
)
from .post_fan_in_qa import (  # noqa: E402
    read_provider_pending_lifecycle_qualification_v2_schema,
    run_provider_pending_lifecycle_qualification_v2,
    validate_provider_pending_lifecycle_qualification_v2,
)
from .post_fan_in_contracts import (  # noqa: E402
    build_lifecycle_inspection_v07,
    commit_local_work_progress,
    inspect_post_fan_in_lifecycle,
    build_local_work_inventory,
    read_lifecycle_inspection_v07_schema,
    read_local_work_inventory_schema,
    validate_lifecycle_inspection_v07,
    validate_local_work_inventory,
    validate_local_work_inventory_against_v05,
    validate_local_work_progress,
)
from .adversarial_trace import (  # noqa: E402
    FIXTURE_NAMES as ADVERSARIAL_TRACE_FIXTURE_NAMES,
    SCHEMA_VERSION as ADVERSARIAL_TRACE_SCHEMA_VERSION,
    build_adversarial_trace_fixture,
    canonical_adversarial_trace_bytes,
    derive_trace_id as derive_adversarial_trace_id,
    derive_trace_sha256 as derive_adversarial_trace_sha256,
    finalize_adversarial_trace,
    native_contradictions,
    read_adversarial_trace_fixture,
    read_adversarial_trace_schema,
    semantic_fingerprint as adversarial_trace_semantic_fingerprint,
    validate_adversarial_trace,
)
from .adversarial_oracle import (  # noqa: E402
    adversarial_safety_violations,
    assert_adversarial_safety,
    assert_adversarial_oracle,
    classify_adversarial_transition,
    evaluate_adversarial_history,
    oracle_semantic_fingerprint,
)
from .adversarial_adapter import (  # noqa: E402
    build_review_no_action_runtime_trace,
    inspect_review_no_action_workspace,
    materialize_review_no_action_workspace,
)
from .adversarial_route_matrix import (  # noqa: E402
    build_adversarial_route_matrix_qualification,
    validate_adversarial_route_matrix_qualification,
)
from .external_authority import (  # noqa: E402
    build_external_authority_refusal,
    build_external_authority_request,
    read_external_authority_request,
    read_external_authority_schema,
    validate_external_authority_grant,
    validate_external_authority_refusal,
    validate_external_authority_request,
)
from .external_authority_v2 import (  # noqa: E402
    build_external_authority_grant_v2,
    build_no_grant_dispatch_result_v2,
    read_external_authority_dispatch_result_v2_schema,
    read_external_authority_grant_v2_schema,
    read_external_authority_v2_fixture,
    validate_authorization_document_v2,
    validate_external_authority_grant_v2,
    validate_no_grant_dispatch_result_v2,
)
from .external_authority_v2_execution import (  # noqa: E402
    ExternalAuthorityV2ExecutionError,
    build_external_authority_v2_command_result,
    build_external_authority_provider_dispatch_result_v3,
    build_external_authority_v2_command_result_v2,
    commit_external_authority_v2_dispatch_intent,
    dispatch_external_authority_v2_intent,
    read_external_authority_intent_result_v2_schema,
    read_external_authority_provider_dispatch_result_v2_schema,
    read_external_authority_provider_dispatch_result_v3_schema,
    read_external_authority_v2_command_result_schema,
    read_external_authority_v2_command_result_v2_schema,
    read_ambiguous_provider_submission_fixture_v1,
    resolve_external_authority_v2_request_payload,
    validate_external_authority_intent_result_v2,
    validate_external_authority_provider_dispatch_result_v2,
    validate_external_authority_provider_dispatch_result_v3,
    validate_external_authority_v2_command_result,
    validate_external_authority_v2_command_result_v2,
    validate_ambiguous_provider_submission_fixture_v1,
)
from .external_authority_qa import (  # noqa: E402
    read_external_authority_qualification_schema,
    run_external_authority_qualification,
    validate_external_authority_qualification_receipt,
)
from .external_authority_v2_qa import (  # noqa: E402
    read_external_authority_v2_qualification_schema,
    run_external_authority_v2_qualification,
    validate_external_authority_v2_qualification,
)
from .payload_recovery_qa import (  # noqa: E402
    read_payload_recovery_qualification_schema,
    run_payload_recovery_qualification,
    validate_payload_recovery_qualification,
)
from .operator_retirement import (  # noqa: E402
    assess_operator_retirement,
    build_operator_retirement_request,
    execute_operator_retirement,
    read_operator_retirement_schema,
    validate_operator_retirement_assessment,
    validate_operator_retirement_request,
    validate_operator_retirement_result,
)
from .operator_retirement_qa import (  # noqa: E402
    read_operator_retirement_qualification_schema,
    run_operator_retirement_qualification,
    validate_operator_retirement_qualification,
)
from .provider_economics import (  # noqa: E402
    MAX_RETRIEVAL_REFERENCES,
    PROVIDER_ECONOMICS_FIXTURE_NAMES,
    SCHEMA_VERSION as PROVIDER_ECONOMICS_SCHEMA_VERSION,
    derive_cohort_identity_sha256,
    derive_revision_id,
    derive_transaction_id,
    finalize_provider_economics_revision,
    project_exact_provider_economics_revision,
    project_bounded_provider_economics_revision,
    read_provider_economics_schema,
    read_provider_economics_fixture,
    read_provider_economics_mutation_corpus,
    validate_provider_economics_revision,
    validate_provider_economics_revision_sequence,
)
from .provider_economics_export import (  # noqa: E402
    EXPORT_SCHEMA_VERSION as PROVIDER_ECONOMICS_EXPORT_SCHEMA_VERSION,
    read_provider_economics_export,
    read_provider_economics_export_schema,
    validate_provider_economics_export,
)
from .provider_economics_qa import (  # noqa: E402
    read_provider_economics_qualification_schema,
    run_provider_economics_qualification,
    validate_provider_economics_qualification,
)

__all__ = [
    "ADVERSARIAL_TRACE_FIXTURE_NAMES",
    "ADVERSARIAL_TRACE_SCHEMA_VERSION",
    "adversarial_trace_semantic_fingerprint",
    "build_adversarial_trace_fixture",
    "canonical_adversarial_trace_bytes",
    "derive_adversarial_trace_id",
    "derive_adversarial_trace_sha256",
    "finalize_adversarial_trace",
    "native_contradictions",
    "read_adversarial_trace_fixture",
    "read_adversarial_trace_schema",
    "validate_adversarial_trace",
    "assert_adversarial_oracle",
    "assert_adversarial_safety",
    "adversarial_safety_violations",
    "classify_adversarial_transition",
    "evaluate_adversarial_history",
    "oracle_semantic_fingerprint",
    "build_review_no_action_runtime_trace",
    "inspect_review_no_action_workspace",
    "materialize_review_no_action_workspace",
    "build_adversarial_route_matrix_qualification",
    "validate_adversarial_route_matrix_qualification",
    "NativeTransitionResultView",
    "ProviderReconciliationAdapters",
    "InitialWaveError",
    "__version__",
    "latest_native_transition_result",
    "build_initial_wave_authority_inputs",
    "build_initial_wave_binding_bundle",
    "build_wave_authorization",
    "preflight_wave_authorization",
    "read_initial_wave_fixture",
    "read_initial_wave_authority_inputs",
    "read_initial_wave_schema",
    "read_native_transition_result",
    "read_bounded_route_parity_traces",
    "read_route_parity_oracle",
    "read_deployed_qa_schema",
    "run_deployed_qa_qualification",
    "inspect_response",
    "read_response_retrieval_diagnostic_schema",
    "reconcile_authoring_provider_cycle",
    "validate_bounded_route_traces",
    "validate_initial_wave",
    "validate_initial_wave_authority_inputs",
    "validate_initial_wave_binding_bundle",
    "validate_initial_wave_binding_bundle_against_wave",
    "validate_initial_wave_fixture",
    "validate_initial_wave_result",
    "validate_wave_authorization_document",
    "validate_route_parity_oracle",
    "validate_deployed_qa_receipt",
    "validate_response_retrieval_diagnostic",
    "validate_transition_journal",
    "validate_lifecycle_inspection_v04",
    "validate_lifecycle_inspection_v05",
    "build_lifecycle_inspection_v06",
    "build_external_authority_request_v2",
    "canonical_utc_instant",
    "inspect_temporal_lifecycle",
    "read_temporal_external_authority_schema",
    "read_temporal_lifecycle_schema",
    "temporal_transition_errors",
    "validate_lifecycle_inspection_v06",
    "validate_external_authority_request_v2",
    "validate_external_authority_request_v2_against_inspection",
    "validate_temporal_transition",
    "run_provider_pending_lifecycle_qualification",
    "read_provider_pending_lifecycle_qualification_v2_schema",
    "run_provider_pending_lifecycle_qualification_v2",
    "validate_provider_pending_lifecycle_qualification_v2",
    "build_lifecycle_inspection_v07",
    "commit_local_work_progress",
    "inspect_post_fan_in_lifecycle",
    "build_local_work_inventory",
    "read_lifecycle_inspection_v07_schema",
    "read_local_work_inventory_schema",
    "validate_lifecycle_inspection_v07",
    "validate_local_work_inventory",
    "validate_local_work_inventory_against_v05",
    "validate_local_work_progress",
    "build_external_authority_request",
    "build_external_authority_refusal",
    "read_external_authority_request",
    "read_external_authority_schema",
    "validate_external_authority_grant",
    "validate_external_authority_refusal",
    "validate_external_authority_request",
    "build_external_authority_grant_v2",
    "build_no_grant_dispatch_result_v2",
    "read_external_authority_dispatch_result_v2_schema",
    "read_external_authority_grant_v2_schema",
    "read_external_authority_v2_fixture",
    "validate_authorization_document_v2",
    "validate_external_authority_grant_v2",
    "validate_no_grant_dispatch_result_v2",
    "ExternalAuthorityV2ExecutionError",
    "build_external_authority_v2_command_result",
    "build_external_authority_provider_dispatch_result_v3",
    "build_external_authority_v2_command_result_v2",
    "commit_external_authority_v2_dispatch_intent",
    "dispatch_external_authority_v2_intent",
    "read_external_authority_intent_result_v2_schema",
    "read_external_authority_provider_dispatch_result_v2_schema",
    "read_external_authority_provider_dispatch_result_v3_schema",
    "read_external_authority_v2_command_result_schema",
    "read_external_authority_v2_command_result_v2_schema",
    "read_ambiguous_provider_submission_fixture_v1",
    "resolve_external_authority_v2_request_payload",
    "validate_external_authority_intent_result_v2",
    "validate_external_authority_provider_dispatch_result_v2",
    "validate_external_authority_provider_dispatch_result_v3",
    "validate_external_authority_v2_command_result",
    "validate_external_authority_v2_command_result_v2",
    "validate_ambiguous_provider_submission_fixture_v1",
    "read_external_authority_qualification_schema",
    "run_external_authority_qualification",
    "validate_external_authority_qualification_receipt",
    "read_external_authority_v2_qualification_schema",
    "run_external_authority_v2_qualification",
    "validate_external_authority_v2_qualification",
    "read_payload_recovery_qualification_schema",
    "run_payload_recovery_qualification",
    "validate_payload_recovery_qualification",
    "assess_operator_retirement",
    "build_operator_retirement_request",
    "execute_operator_retirement",
    "read_operator_retirement_schema",
    "validate_operator_retirement_assessment",
    "validate_operator_retirement_request",
    "validate_operator_retirement_result",
    "read_operator_retirement_qualification_schema",
    "run_operator_retirement_qualification",
    "validate_operator_retirement_qualification",
    "MAX_RETRIEVAL_REFERENCES",
    "PROVIDER_ECONOMICS_FIXTURE_NAMES",
    "PROVIDER_ECONOMICS_SCHEMA_VERSION",
    "derive_cohort_identity_sha256",
    "derive_revision_id",
    "derive_transaction_id",
    "finalize_provider_economics_revision",
    "project_exact_provider_economics_revision",
    "project_bounded_provider_economics_revision",
    "read_provider_economics_schema",
    "read_provider_economics_fixture",
    "read_provider_economics_mutation_corpus",
    "validate_provider_economics_revision",
    "validate_provider_economics_revision_sequence",
    "PROVIDER_ECONOMICS_EXPORT_SCHEMA_VERSION",
    "read_provider_economics_export",
    "read_provider_economics_export_schema",
    "validate_provider_economics_export",
    "read_provider_economics_qualification_schema",
    "run_provider_economics_qualification",
    "validate_provider_economics_qualification",
]
