"""AstroWoof natal semantic-basis extraction and authoring runtime."""

from importlib.metadata import PackageNotFoundError, version
import logging


# Library consumers should not receive surprise stderr output merely by importing
# SBE.  Command entry points install the operational handler explicitly.
logging.getLogger(__name__).addHandler(logging.NullHandler())

try:
    __version__ = version("astrowoof-natal-authoring")
except PackageNotFoundError:
    __version__ = "0.4.0.dev0"

from .reconciliation import (  # noqa: E402
    ProviderReconciliationAdapters,
    reconcile_authoring_provider_cycle,
)
from .native_transitions import (  # noqa: E402
    NativeTransitionResultView,
    latest_native_transition_result,
    read_native_transition_result,
    validate_native_publication_receipt,
    validate_transition_journal,
)
from .native_transition_availability import (  # noqa: E402
    NativeTransitionAvailabilityError,
    NativeTransitionAvailabilityView,
    read_native_transition_result_availability,
    read_native_transition_result_availability_schema,
    validate_native_transition_result_availability,
)
from .operator_disposition import (  # noqa: E402
    build_operator_disposition_assessment,
    logical_workspace_root_id,
    read_operator_disposition_assessment,
    read_operator_disposition_assessment_schema,
    validate_operator_disposition_assessment,
)
from .operator_disposition_fixtures import (  # noqa: E402
    read_operator_disposition_fixtures,
    validate_operator_disposition_fixtures,
)
from .operator_disposition_qa import (  # noqa: E402
    read_operator_disposition_qualification_schema,
    run_operator_disposition_qualification,
    validate_operator_disposition_qualification,
)
from .run_report import (  # noqa: E402
    build_report_from_text,
    parse_trace_text,
    read_run_evolution_report,
    read_run_evolution_report_schema,
    render_report_html,
    render_report_markdown,
    render_report_mermaid,
    validate_run_evolution_report,
)
from .run_report_qa import (  # noqa: E402
    read_run_report_qualification_schema,
    run_run_report_qualification,
    validate_run_report_qualification,
)
from .theme_group_policy_qa import (  # noqa: E402
    read_theme_group_policy_qualification_schema,
    run_theme_group_policy_qualification,
    validate_theme_group_policy_qualification,
)
from .route_parity import (  # noqa: E402
    read_bounded_route_parity_traces,
    read_route_parity_oracle,
    validate_bounded_route_traces,
    validate_route_parity_oracle,
)
from .initial_wave import (  # noqa: E402
    InitialWaveError,
    build_initial_wave_binding_bundle,
    build_wave_authorization,
    preflight_wave_authorization,
    validate_initial_wave,
    validate_initial_wave_binding_bundle,
    validate_initial_wave_binding_bundle_against_wave,
    validate_initial_wave_result,
    validate_wave_authorization_document,
)
from .initial_wave_contract import (  # noqa: E402
    build_initial_wave_authority_inputs,
    read_initial_wave_authority_inputs,
    read_initial_wave_fixture,
    read_initial_wave_schema,
    validate_initial_wave_fixture,
    validate_initial_wave_authority_inputs,
)
from .deployed_qa import (  # noqa: E402
    read_deployed_qa_schema,
    run_deployed_qa_qualification,
    validate_deployed_qa_receipt,
)
from .response_diagnostics import (  # noqa: E402
    inspect_response,
    read_response_retrieval_diagnostic_schema,
    validate_response_retrieval_diagnostic,
)
from .lifecycle_contracts import (  # noqa: E402
    validate_lifecycle_inspection_v04,
    validate_lifecycle_inspection_v05,
)
from .temporal_lifecycle import (  # noqa: E402
    build_external_authority_request_v2,
    build_lifecycle_inspection_v06,
    canonical_utc_instant,
    inspect_temporal_lifecycle,
    read_temporal_external_authority_schema,
    read_temporal_lifecycle_schema,
    temporal_transition_errors,
    validate_external_authority_request_v2,
    validate_external_authority_request_v2_against_inspection,
    validate_lifecycle_inspection_v06,
    validate_temporal_transition,
)
from .pending_lifecycle_qa import (  # noqa: E402
    run_provider_pending_lifecycle_qualification,
)
from .terminal_review_contracts import (  # noqa: E402
    build_terminal_action_dispositions,
    build_terminal_review_command_result,
    build_terminal_review_result_v02,
    build_zero_action_terminal_review_command_result,
    build_zero_action_terminal_review_result_v03,
    read_terminal_review_command_result_schema,
    read_terminal_review_result_v02_schema,
    read_zero_action_terminal_review_command_result_schema,
    read_zero_action_terminal_review_result_v03_schema,
    validate_terminal_review_command_result,
    validate_terminal_review_command_result_against_publication,
    validate_terminal_review_result_v02,
    validate_terminal_review_result_v02_against_api_actions,
    validate_terminal_review_result_v02_against_receipt,
    validate_zero_action_terminal_review_command_result,
    validate_zero_action_terminal_review_command_result_against_publication,
    validate_zero_action_terminal_review_result_v03,
    validate_zero_action_terminal_review_result_v03_against_receipt,
)
from .terminal_review_qa import (  # noqa: E402
    read_terminal_review_qualification_schema,
    read_terminal_review_qualification_v02_schema,
    run_terminal_review_qualification,
    run_terminal_review_qualification_v02,
    validate_terminal_review_qualification,
    validate_terminal_review_qualification_v02,
)
from .post_fan_in_qa import (  # noqa: E402
    read_provider_pending_lifecycle_qualification_v2_schema,
    run_provider_pending_lifecycle_qualification_v2,
    validate_provider_pending_lifecycle_qualification_v2,
)
from .post_fan_in_contracts import (  # noqa: E402
    build_lifecycle_inspection_v07,
    commit_local_work_progress,
    inspect_post_fan_in_lifecycle,
    build_local_work_inventory,
    read_lifecycle_inspection_v07_schema,
    read_local_work_inventory_schema,
    validate_lifecycle_inspection_v07,
    validate_local_work_inventory,
    validate_local_work_inventory_against_v05,
    validate_local_work_progress,
)
from .retry_lineage_contracts import (  # noqa: E402
    ATTEMPT_KEY_SERIALIZATION,
    LIFECYCLE_INSPECTION_SCHEMA_V0_8,
    RETRY_LINEAGE_SCHEMA,
    build_lifecycle_inspection_v08,
    build_retry_lineage_inventory,
    derive_retry_attempt_key,
    read_retry_lineage_schema,
    read_lifecycle_inspection_v08_schema,
    read_lifecycle_inspection_v08_fixture,
    validate_lifecycle_inspection_v08,
    validate_retry_lineage_inventory,
    retry_lineage_inventory_from_state,
    assert_retry_lineage_forward_dispatch_safe,
    inspect_retry_lineage_lifecycle,
)
from .retry_lineage_qa import (  # noqa: E402
    read_retry_lineage_qualification_schema,
    run_retry_lineage_qualification,
    validate_retry_lineage_qualification,
)
from .legacy_local_work_upgrade_qa import (  # noqa: E402
    build_legacy_local_work_upgrade_bundle,
    read_legacy_local_work_upgrade_bundle_schema,
    read_legacy_local_work_upgrade_fixture,
    read_legacy_local_work_upgrade_qualification_schema,
    run_legacy_local_work_upgrade_qualification,
    validate_legacy_local_work_upgrade_bundle,
    validate_legacy_local_work_upgrade_qualification,
)
from .generic_dispatch_refusal import (  # noqa: E402
    build_generic_provider_dispatch_refusal,
    read_generic_provider_dispatch_refusal_schema,
    validate_generic_provider_dispatch_refusal,
)
from .duplicate_submission_fence_fixtures import (  # noqa: E402
    read_duplicate_submission_fence_fixtures,
    read_duplicate_submission_fence_fixtures_schema,
    validate_duplicate_submission_fence_fixtures,
)
from .duplicate_submission_fence_qa import (  # noqa: E402
    read_duplicate_submission_fence_qualification_schema,
    run_duplicate_submission_fence_qualification,
    validate_duplicate_submission_fence_qualification,
)
from .adversarial_trace import (  # noqa: E402
    FIXTURE_NAMES as ADVERSARIAL_TRACE_FIXTURE_NAMES,
    SCHEMA_VERSION as ADVERSARIAL_TRACE_SCHEMA_VERSION,
    build_adversarial_trace_fixture,
    canonical_adversarial_trace_bytes,
    derive_trace_id as derive_adversarial_trace_id,
    derive_trace_sha256 as derive_adversarial_trace_sha256,
    finalize_adversarial_trace,
    native_contradictions,
    read_adversarial_trace_fixture,
    read_adversarial_trace_schema,
    semantic_fingerprint as adversarial_trace_semantic_fingerprint,
    validate_adversarial_trace,
)
from .adversarial_oracle import (  # noqa: E402
    adversarial_safety_violations,
    assert_adversarial_safety,
    assert_adversarial_oracle,
    classify_adversarial_transition,
    evaluate_adversarial_history,
    oracle_semantic_fingerprint,
)
from .adversarial_adapter import (  # noqa: E402
    build_review_no_action_runtime_trace,
    inspect_review_no_action_workspace,
    materialize_review_no_action_workspace,
)
from .adversarial_route_matrix import (  # noqa: E402
    build_adversarial_route_matrix_qualification,
    validate_adversarial_route_matrix_qualification,
)
from .adversarial_explorer import (  # noqa: E402
    advance_explorer_clock,
    build_action_binding_projection,
    run_systematic_explorer_qualification,
    validate_action_binding_projection,
    validate_explorer_clock_state,
    validate_systematic_explorer_qualification,
)
from .adversarial_campaign import (  # noqa: E402
    replay_seeded_walk,
    run_seeded_campaign_qualification,
    run_seeded_walk,
    shrink_stutter_counterexample,
    validate_seeded_campaign_qualification,
)
from .adversarial_qa import (  # noqa: E402
    read_adversarial_qualification_schema,
    run_adversarial_qualification,
    validate_adversarial_qualification,
)
from .adversarial_consumer import (  # noqa: E402
    read_adversarial_consumer_catalog,
    validate_adversarial_consumer_catalog,
)
from .external_authority import (  # noqa: E402
    build_external_authority_refusal,
    build_external_authority_request,
    read_external_authority_request,
    read_external_authority_schema,
    validate_external_authority_grant,
    validate_external_authority_refusal,
    validate_external_authority_request,
)
from .external_authority_v2 import (  # noqa: E402
    build_external_authority_grant_v2,
    build_no_grant_dispatch_result_v2,
    read_external_authority_dispatch_result_v2_schema,
    read_external_authority_grant_v2_schema,
    read_external_authority_v2_fixture,
    validate_authorization_document_v2,
    validate_external_authority_grant_v2,
    validate_no_grant_dispatch_result_v2,
)
from .external_authority_v2_execution import (  # noqa: E402
    ExternalAuthorityV2ExecutionError,
    build_external_authority_v2_command_result,
    build_external_authority_provider_dispatch_result_v3,
    build_external_authority_provider_dispatch_result_v4,
    build_external_authority_provider_dispatch_result_v5,
    build_external_authority_v2_command_result_v2,
    build_external_authority_v2_command_result_v3,
    build_external_authority_v2_command_result_v4,
    commit_external_authority_v2_dispatch_intent,
    dispatch_external_authority_v2_intent,
    read_external_authority_intent_result_v2_schema,
    read_external_authority_provider_dispatch_result_v2_schema,
    read_external_authority_provider_dispatch_result_v3_schema,
    read_external_authority_provider_dispatch_result_v4_schema,
    read_external_authority_provider_dispatch_result_v5_schema,
    read_external_authority_v2_command_result_schema,
    read_external_authority_v2_command_result_v2_schema,
    read_external_authority_v2_command_result_v3_schema,
    read_external_authority_v2_command_result_v4_schema,
    read_ambiguous_provider_submission_fixture_v1,
    resolve_external_authority_v2_request_payload,
    validate_external_authority_intent_result_v2,
    validate_external_authority_provider_dispatch_result_v2,
    validate_external_authority_provider_dispatch_result_v3,
    validate_external_authority_provider_dispatch_result_v4,
    validate_external_authority_provider_dispatch_result_v5,
    validate_external_authority_v2_command_result,
    validate_external_authority_v2_command_result_v2,
    validate_external_authority_v2_command_result_v3,
    validate_external_authority_v2_command_result_v4,
    validate_ambiguous_provider_submission_fixture_v1,
)
from .external_authority_qa import (  # noqa: E402
    read_external_authority_qualification_schema,
    run_external_authority_qualification,
    validate_external_authority_qualification_receipt,
)
from .external_authority_v2_qa import (  # noqa: E402
    read_external_authority_v2_qualification_schema,
    run_external_authority_v2_qualification,
    validate_external_authority_v2_qualification,
)
from .intent_retirement_qa import (  # noqa: E402
    read_intent_retirement_qualification_schema,
    run_intent_retirement_qualification,
    validate_intent_retirement_qualification,
)
from .payload_recovery_qa import (  # noqa: E402
    read_payload_recovery_qualification_schema,
    run_payload_recovery_qualification,
    validate_payload_recovery_qualification,
)
from .operator_retirement import (  # noqa: E402
    assess_operator_retirement,
    build_operator_retirement_request,
    execute_operator_retirement,
    read_operator_retirement_schema,
    validate_operator_retirement_assessment,
    validate_operator_retirement_request,
    validate_operator_retirement_result,
)
from .operator_retirement_qa import (  # noqa: E402
    read_operator_retirement_qualification_schema,
    run_operator_retirement_qualification,
    validate_operator_retirement_qualification,
)
from .post_fan_in_retry_qa import (  # noqa: E402
    read_post_fan_in_retry_fixture,
    read_post_fan_in_retry_inspection_bundle_schema,
    read_post_fan_in_retry_qualification_schema,
    run_post_fan_in_retry_inspection_bundle,
    run_post_fan_in_retry_qualification,
    validate_post_fan_in_retry_inspection_bundle,
    validate_post_fan_in_retry_qualification,
)
from .happy_path_qa import (  # noqa: E402
    read_ordinary_v2_happy_path_bundle_schema,
    read_ordinary_v2_happy_path_fixture,
    read_ordinary_v2_happy_path_qualification_schema,
    run_ordinary_v2_happy_path_bundle,
    run_ordinary_v2_happy_path_qualification,
    validate_ordinary_v2_happy_path_bundle,
    validate_ordinary_v2_happy_path_qualification,
)
from .provider_economics import (  # noqa: E402
    MAX_RETRIEVAL_REFERENCES,
    PROVIDER_ECONOMICS_FIXTURE_NAMES,
    SCHEMA_VERSION as PROVIDER_ECONOMICS_SCHEMA_VERSION,
    derive_cohort_identity_sha256,
    derive_revision_id,
    derive_transaction_id,
    finalize_provider_economics_revision,
    project_exact_provider_economics_revision,
    project_bounded_provider_economics_revision,
    read_provider_economics_schema,
    read_provider_economics_fixture,
    read_provider_economics_mutation_corpus,
    validate_provider_economics_revision,
    validate_provider_economics_revision_sequence,
)
from .provider_economics_export import (  # noqa: E402
    EXPORT_SCHEMA_VERSION as PROVIDER_ECONOMICS_EXPORT_SCHEMA_VERSION,
    read_provider_economics_export,
    read_provider_economics_export_schema,
    validate_provider_economics_export,
)
from .provider_economics_qa import (  # noqa: E402
    read_provider_economics_qualification_schema,
    run_provider_economics_qualification,
    validate_provider_economics_qualification,
)

__all__ = [
    "ADVERSARIAL_TRACE_FIXTURE_NAMES",
    "ADVERSARIAL_TRACE_SCHEMA_VERSION",
    "adversarial_trace_semantic_fingerprint",
    "build_adversarial_trace_fixture",
    "canonical_adversarial_trace_bytes",
    "derive_adversarial_trace_id",
    "derive_adversarial_trace_sha256",
    "finalize_adversarial_trace",
    "native_contradictions",
    "read_adversarial_trace_fixture",
    "read_adversarial_trace_schema",
    "validate_adversarial_trace",
    "assert_adversarial_oracle",
    "assert_adversarial_safety",
    "adversarial_safety_violations",
    "classify_adversarial_transition",
    "evaluate_adversarial_history",
    "oracle_semantic_fingerprint",
    "build_review_no_action_runtime_trace",
    "inspect_review_no_action_workspace",
    "materialize_review_no_action_workspace",
    "build_adversarial_route_matrix_qualification",
    "validate_adversarial_route_matrix_qualification",
    "build_action_binding_projection",
    "advance_explorer_clock",
    "run_systematic_explorer_qualification",
    "validate_action_binding_projection",
    "validate_explorer_clock_state",
    "validate_systematic_explorer_qualification",
    "replay_seeded_walk",
    "run_seeded_campaign_qualification",
    "run_seeded_walk",
    "shrink_stutter_counterexample",
    "validate_seeded_campaign_qualification",
    "read_adversarial_qualification_schema",
    "run_adversarial_qualification",
    "validate_adversarial_qualification",
    "read_adversarial_consumer_catalog",
    "validate_adversarial_consumer_catalog",
    "NativeTransitionResultView",
    "NativeTransitionAvailabilityError",
    "NativeTransitionAvailabilityView",
    "ProviderReconciliationAdapters",
    "InitialWaveError",
    "__version__",
    "latest_native_transition_result",
    "build_initial_wave_authority_inputs",
    "build_initial_wave_binding_bundle",
    "build_wave_authorization",
    "preflight_wave_authorization",
    "read_initial_wave_fixture",
    "read_initial_wave_authority_inputs",
    "read_initial_wave_schema",
    "read_native_transition_result",
    "read_native_transition_result_availability",
    "read_native_transition_result_availability_schema",
    "build_operator_disposition_assessment",
    "logical_workspace_root_id",
    "read_operator_disposition_assessment",
    "read_operator_disposition_assessment_schema",
    "validate_operator_disposition_assessment",
    "read_operator_disposition_fixtures",
    "validate_operator_disposition_fixtures",
    "read_operator_disposition_qualification_schema",
    "run_operator_disposition_qualification",
    "validate_operator_disposition_qualification",
    "validate_native_publication_receipt",
    "validate_native_transition_result_availability",
    "read_bounded_route_parity_traces",
    "read_route_parity_oracle",
    "read_deployed_qa_schema",
    "run_deployed_qa_qualification",
    "inspect_response",
    "read_response_retrieval_diagnostic_schema",
    "reconcile_authoring_provider_cycle",
    "validate_bounded_route_traces",
    "validate_initial_wave",
    "validate_initial_wave_authority_inputs",
    "validate_initial_wave_binding_bundle",
    "validate_initial_wave_binding_bundle_against_wave",
    "validate_initial_wave_fixture",
    "validate_initial_wave_result",
    "validate_wave_authorization_document",
    "validate_route_parity_oracle",
    "validate_deployed_qa_receipt",
    "validate_response_retrieval_diagnostic",
    "validate_transition_journal",
    "build_terminal_action_dispositions",
    "build_terminal_review_command_result",
    "build_terminal_review_result_v02",
    "build_zero_action_terminal_review_command_result",
    "build_zero_action_terminal_review_result_v03",
    "read_terminal_review_command_result_schema",
    "read_terminal_review_result_v02_schema",
    "read_zero_action_terminal_review_command_result_schema",
    "read_zero_action_terminal_review_result_v03_schema",
    "validate_terminal_review_result_v02",
    "validate_zero_action_terminal_review_result_v03",
    "validate_terminal_review_command_result",
    "validate_zero_action_terminal_review_command_result",
    "validate_terminal_review_command_result_against_publication",
    "validate_zero_action_terminal_review_command_result_against_publication",
    "validate_terminal_review_result_v02_against_api_actions",
    "validate_terminal_review_result_v02_against_receipt",
    "validate_zero_action_terminal_review_result_v03_against_receipt",
    "read_terminal_review_qualification_schema",
    "read_terminal_review_qualification_v02_schema",
    "run_terminal_review_qualification",
    "run_terminal_review_qualification_v02",
    "validate_terminal_review_qualification",
    "validate_terminal_review_qualification_v02",
    "validate_lifecycle_inspection_v04",
    "validate_lifecycle_inspection_v05",
    "build_lifecycle_inspection_v06",
    "build_external_authority_request_v2",
    "canonical_utc_instant",
    "inspect_temporal_lifecycle",
    "read_temporal_external_authority_schema",
    "read_temporal_lifecycle_schema",
    "temporal_transition_errors",
    "validate_lifecycle_inspection_v06",
    "validate_external_authority_request_v2",
    "validate_external_authority_request_v2_against_inspection",
    "validate_temporal_transition",
    "run_provider_pending_lifecycle_qualification",
    "read_provider_pending_lifecycle_qualification_v2_schema",
    "run_provider_pending_lifecycle_qualification_v2",
    "validate_provider_pending_lifecycle_qualification_v2",
    "build_lifecycle_inspection_v07",
    "commit_local_work_progress",
    "inspect_post_fan_in_lifecycle",
    "build_local_work_inventory",
    "read_lifecycle_inspection_v07_schema",
    "read_local_work_inventory_schema",
    "validate_lifecycle_inspection_v07",
    "validate_local_work_inventory",
    "validate_local_work_inventory_against_v05",
    "validate_local_work_progress",
    "ATTEMPT_KEY_SERIALIZATION",
    "LIFECYCLE_INSPECTION_SCHEMA_V0_8",
    "RETRY_LINEAGE_SCHEMA",
    "build_lifecycle_inspection_v08",
    "build_retry_lineage_inventory",
    "derive_retry_attempt_key",
    "read_retry_lineage_schema",
    "read_lifecycle_inspection_v08_schema",
    "read_lifecycle_inspection_v08_fixture",
    "validate_lifecycle_inspection_v08",
    "validate_retry_lineage_inventory",
    "retry_lineage_inventory_from_state",
    "assert_retry_lineage_forward_dispatch_safe",
    "inspect_retry_lineage_lifecycle",
    "read_retry_lineage_qualification_schema",
    "run_retry_lineage_qualification",
    "validate_retry_lineage_qualification",
    "build_generic_provider_dispatch_refusal",
    "read_generic_provider_dispatch_refusal_schema",
    "validate_generic_provider_dispatch_refusal",
    "read_duplicate_submission_fence_fixtures",
    "read_duplicate_submission_fence_fixtures_schema",
    "validate_duplicate_submission_fence_fixtures",
    "read_duplicate_submission_fence_qualification_schema",
    "run_duplicate_submission_fence_qualification",
    "validate_duplicate_submission_fence_qualification",
    "build_external_authority_request",
    "build_external_authority_refusal",
    "read_external_authority_request",
    "read_external_authority_schema",
    "validate_external_authority_grant",
    "validate_external_authority_refusal",
    "validate_external_authority_request",
    "build_external_authority_grant_v2",
    "build_no_grant_dispatch_result_v2",
    "read_external_authority_dispatch_result_v2_schema",
    "read_external_authority_grant_v2_schema",
    "read_external_authority_v2_fixture",
    "validate_authorization_document_v2",
    "validate_external_authority_grant_v2",
    "validate_no_grant_dispatch_result_v2",
    "ExternalAuthorityV2ExecutionError",
    "build_external_authority_v2_command_result",
    "build_external_authority_provider_dispatch_result_v3",
    "build_external_authority_provider_dispatch_result_v4",
    "build_external_authority_provider_dispatch_result_v5",
    "build_external_authority_v2_command_result_v2",
    "build_external_authority_v2_command_result_v3",
    "build_external_authority_v2_command_result_v4",
    "commit_external_authority_v2_dispatch_intent",
    "dispatch_external_authority_v2_intent",
    "read_external_authority_intent_result_v2_schema",
    "read_external_authority_provider_dispatch_result_v2_schema",
    "read_external_authority_provider_dispatch_result_v3_schema",
    "read_external_authority_provider_dispatch_result_v4_schema",
    "read_external_authority_provider_dispatch_result_v5_schema",
    "read_external_authority_v2_command_result_schema",
    "read_external_authority_v2_command_result_v2_schema",
    "read_external_authority_v2_command_result_v3_schema",
    "read_external_authority_v2_command_result_v4_schema",
    "read_ambiguous_provider_submission_fixture_v1",
    "resolve_external_authority_v2_request_payload",
    "validate_external_authority_intent_result_v2",
    "validate_external_authority_provider_dispatch_result_v2",
    "validate_external_authority_provider_dispatch_result_v3",
    "validate_external_authority_provider_dispatch_result_v4",
    "validate_external_authority_provider_dispatch_result_v5",
    "validate_external_authority_v2_command_result",
    "validate_external_authority_v2_command_result_v2",
    "validate_external_authority_v2_command_result_v3",
    "validate_external_authority_v2_command_result_v4",
    "validate_ambiguous_provider_submission_fixture_v1",
    "read_external_authority_qualification_schema",
    "run_external_authority_qualification",
    "validate_external_authority_qualification_receipt",
    "read_external_authority_v2_qualification_schema",
    "read_intent_retirement_qualification_schema",
    "run_intent_retirement_qualification",
    "validate_intent_retirement_qualification",
    "run_external_authority_v2_qualification",
    "validate_external_authority_v2_qualification",
    "read_payload_recovery_qualification_schema",
    "run_payload_recovery_qualification",
    "validate_payload_recovery_qualification",
    "assess_operator_retirement",
    "build_operator_retirement_request",
    "execute_operator_retirement",
    "read_operator_retirement_schema",
    "validate_operator_retirement_assessment",
    "validate_operator_retirement_request",
    "validate_operator_retirement_result",
    "read_operator_retirement_qualification_schema",
    "run_operator_retirement_qualification",
    "validate_operator_retirement_qualification",
    "read_post_fan_in_retry_fixture",
    "read_post_fan_in_retry_inspection_bundle_schema",
    "read_post_fan_in_retry_qualification_schema",
    "run_post_fan_in_retry_inspection_bundle",
    "run_post_fan_in_retry_qualification",
    "validate_post_fan_in_retry_inspection_bundle",
    "validate_post_fan_in_retry_qualification",
    "build_legacy_local_work_upgrade_bundle",
    "read_legacy_local_work_upgrade_bundle_schema",
    "read_legacy_local_work_upgrade_fixture",
    "read_legacy_local_work_upgrade_qualification_schema",
    "run_legacy_local_work_upgrade_qualification",
    "validate_legacy_local_work_upgrade_bundle",
    "validate_legacy_local_work_upgrade_qualification",
    "read_ordinary_v2_happy_path_bundle_schema",
    "read_ordinary_v2_happy_path_fixture",
    "read_ordinary_v2_happy_path_qualification_schema",
    "run_ordinary_v2_happy_path_bundle",
    "run_ordinary_v2_happy_path_qualification",
    "validate_ordinary_v2_happy_path_bundle",
    "validate_ordinary_v2_happy_path_qualification",
    "MAX_RETRIEVAL_REFERENCES",
    "PROVIDER_ECONOMICS_FIXTURE_NAMES",
    "PROVIDER_ECONOMICS_SCHEMA_VERSION",
    "derive_cohort_identity_sha256",
    "derive_revision_id",
    "derive_transaction_id",
    "finalize_provider_economics_revision",
    "project_exact_provider_economics_revision",
    "project_bounded_provider_economics_revision",
    "read_provider_economics_schema",
    "read_provider_economics_fixture",
    "read_provider_economics_mutation_corpus",
    "validate_provider_economics_revision",
    "validate_provider_economics_revision_sequence",
    "PROVIDER_ECONOMICS_EXPORT_SCHEMA_VERSION",
    "read_provider_economics_export",
    "read_provider_economics_export_schema",
    "validate_provider_economics_export",
    "read_provider_economics_qualification_schema",
    "run_provider_economics_qualification",
    "validate_provider_economics_qualification",
    "build_report_from_text",
    "parse_trace_text",
    "read_run_evolution_report",
    "read_run_evolution_report_schema",
    "render_report_html",
    "render_report_markdown",
    "render_report_mermaid",
    "validate_run_evolution_report",
    "read_run_report_qualification_schema",
    "run_run_report_qualification",
    "validate_run_report_qualification",
    "read_theme_group_policy_qualification_schema",
    "run_theme_group_policy_qualification",
    "validate_theme_group_policy_qualification",
]
